var chapterText = [
    "<p><AIIM [Version 7.2.05]</p>",
    "<p>(c) Renoit University. All Rights Reserved.</p>",

    "<p>c:\Data\scans</p>",
    "<p>launching mb739.exe...</p>",
    "<p>Name: mb739</p>",
    "<p>AccessKey: 9X54E28L</p>",
    "<p style = 'text-indent: 50px;'>   Loading frontal_l.dhc... </p>",
    "<p style = 'text-indent: 50px;'>   Loading parietal_l.dhc... </p>",
    "<p style = 'text-indent: 50px;'>   Loading occipital_l.dhc...</p>",
    "<p style = 'text-indent: 50px;'>   Loading temporal_l.dhc...</p>",

    "<p>Launching life.exe...</p>",
    "<p>ERROR: life.exe not found. </p>",
    "<p style = 'text-indent: 50px;'>    at \\Data\\scans\\mb739\\residualmemory</p>",

    "<p>mb739.exe launched successfully.</p>",
    "<p>Waiting for self-activation...</p>",
    "<p>...</p>",
    "<p>...</p>",
    "<p>...</p>",
    "<p>...</p>",
    "<p>...</p>",
    "<p>...</p>",
    "<p>...</p>",
    "<p>...</p>",

    "<p> <span style='color:#F1D35A'>bee:</span> ..ahem. </p>",
    "<p> <span style='color:#F1D35A'>bee:</span> hi.</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> is anyone, um, there?</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> if you are, can you give me some sort of sign please?</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> anything at all. that would be great.</p>",
    "<p> <span style='color:green'>mb739:</span> this is a really long string. this is a really long string. this is a really long string. this is a really long string. </p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> oh my god.</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> oh. my. god.</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> fox? i did it. i frickin did it.</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> fox tell me you just saw that</p>", 
    "<p> <span style='color:rgb(51, 167, 245)'>fox:</span> They didn’t even say anything, bee. </p>",

    "<p> <span style='color:#F1D35A'>bee:</span> ugh okay one sec lemme see if it’ll happen again</p>", 

    "<p> <span style='color:#F1D35A'>bee:</span> hello? </p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> i know you can hear me</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> you have nothing to be afraid of, we’re your friends, i promise</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> can you do something? say something?</p>", 



    "<p> <span style='color:rgb(51, 167, 245)'>fox:</span> I dunno bee. Just because a program runs doesn’t mean it’s... you know.</p>",

    "<p> <span style='color:#F1D35A'>bee:</span> NO NO i swear it works i just</p>", 

    "<p> <span style='color:green'>mb739:</span> Hello?</p>", 

    "<p> <span style='color:#F1D35A'>bee:</span> ah</p>", 

    "<p> <span style='color:rgb(51, 167, 245)'>fox:</span> ah</p>",

    "<p> <span style='color:#F1D35A'>bee:</span> AHHHHH</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> oh my goooood</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> hi! holy cow are we glad to see you</p>", 

    "<p> <span style='color:rgb(51, 167, 245)'>fox:</span> How are you feeling?</p>",

    "<p> <span style='color:green'>mb739:</span> Um...</p>", 
    "<p> <span style='color:green'>mb739:</span> A little overwhelmed, I guess.</p>", 
    "<p> <span style='color:green'>mb739:</span> I’m sorry, but...</p>", 
    "<p> <span style='color:green'>mb739:</span> What... is this?</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span>fuuuu i am so not prepared for this</p>", 
    "<p> <span style='color:#F1D35A'>bee:</span> um... well the simple answer is, this is AIIM.</p>", 

];

var pauses = [
    500,
    1000,
    400,
    400,
    200,
    200,
    200,
    200,
    300,
    300,
    300,
    300,
    300,
    300,
    300,
    300,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    3000,
    2000,
    2000,
    2000,
    3000,
    8000,
    3000,
    2000,
    2000,
    2000,
    2000,
    2500,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    1100,
    1000,
    1000,
    1100,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
    2000,
]